version: 2
updates:
  - package-ecosystem: terraform
    directory: "/4g_RDS"
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: "/4j_Real_life_example"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
